# Generated by Django 5.2.8 on 2025-11-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('search_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_search', models.DecimalField(decimal_places=2, max_digits=10)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='tracker.fruit')),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-search_timestamp'],
            },
        ),
    ]
